import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased relative`}>
        <Image
          src="/img/png/bg.png"
          width={1920}
          height={1080}
          alt=""
          className="fixed h-full w-full z-[-1] object-cover"
        />
        <div className="max-w-[1760px] mx-auto">{children}</div>
      </body>
    </html>
  );
}
