import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
import { CtaScroll } from "@/ui/components/ctaScroll";

export const metadata: Metadata = {
  title: "CBK-portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased relative min-h-screen `}>
        <Image
          src="/img/png/bg.png"
          width={1920}
          height={1080}
          alt=""
          className="fixed h-full w-full z-[-1] object-cover"
        />
        <div className="max-w-[1760px] mx-auto px-4">{children}</div>
        <div className="fixed bottom-4 right-4">
          <CtaScroll variant="contact" />
        </div>
      </body>
    </html>
  );
}
